apiVersion: v1
kind: Template
metadata:
  name: acs-cve-prom-exporter
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: acs-cve-prom-exporter
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      ignore-check.kube-linter.io/minimum-three-replicas: "multiple replicas is multiple cost"
      ignore-check.kube-linter.io/unset-cpu-requirements: "no cpu limits"
    labels:
      app: acs-cve-prom-exporter
    name: acs-cve-prom-exporter
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: acs-cve-prom-exporter
    template:
      metadata:
        labels:
          app: acs-cve-prom-exporter
      spec:
        serviceAccountName: acs-cve-prom-exporter
        containers:
        - name: acs-cve-prom-exporter
          image: ${IMAGE}:${IMAGE_TAG}
          ports:
          - containerPort: 9090
            name: http
            protocol: TCP
          env:
          - name: ACS_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: acs-cve-prom-exporter
                key: url
          - name: ACS_TOKEN
            valueFrom:
              secretKeyRef:
                name: acs-cve-prom-exporter
                key: token
          resources:
            limits:
              memory: ${MEMORY_LIMITS}
            requests:
              cpu: ${CPU_REQUESTS}
              memory: ${MEMORY_REQUESTS}
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /metrics
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            initialDelaySeconds: 10
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /metrics
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            initialDelaySeconds: 10
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: acs-cve-prom-exporter
    name: acs-cve-prom-exporter
  spec:
    selector:
      app: acs-cve-prom-exporter
    ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
    type: ClusterIP
parameters:
- name: IMAGE
  value: quay.io/app-sre/acs-cve-prom-exporter
- name: IMAGE_TAG
  value: latest
- name: REPLICAS
  value: "1"
- name: CPU_REQUESTS
  value: 50m
- name: MEMORY_LIMITS
  value: 150Mi
- name: MEMORY_REQUESTS
  value: 150Mi
